# Dados de conexao com banco H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Configuracao do cliente web do banco H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracao para mostrar o SQL no console E criar o DDL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o banco seja recriado do zero a cada execução
spring.jpa.hibernate.ddl-auto=create-drop

# Importante para Spring Boot 3+: Garante que o import.sql rode DEPOIS das tabelas serem criadas
spring.jpa.defer-datasource-initialization=true